sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DB=mysql
      services: mysql
    - php: 7.0
      env: DB=postgres
      services: postgresql
    - php: 7.1
      env: DB=mysql
      services: mysql
    - php: 7.1
      env: DB=postgres
      services: postgresql
    - php: 7.2
      env: DB=mysql
      services: mysql
    - php: 7.2
      env: DB=postgres
      services: postgresql

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database fans;' -U postgres; echo "$DB"; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS fans;'; echo "$DB"; fi"
    - sh -c "php ./.travis.php "$DB""
    - php -r "file_exists('.env') || copy('.env.travis', '.env');"

install:
    - composer install
    - php fans key:generate
    - php fans key:generate --force

script:
    - php fans migrate -vvv
    - php fans db:seed -vvv
    - php fans vendor:publish --all -vvv
    - php vendor/bin/phpunit
