name: ovo
description: OvO is a Dart-first schema declaration and validation library.
version: 0.0.2
repository: https://github.com/medz/ovo

environment:
  sdk: ^3.1.5

dependencies:
  _fe_analyzer_shared: ^69.0.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
